### ISSUE TITLE
[Migration Tools] Initial XS apps migration tool

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#249]
- [x] Research where exactly to add the the UI wizard for XS app migrations - https://github.com/SAP/xsk/issues/232
- [x] Create a PoC of the UI for the migration tools - https://github.com/SAP/xsk/issues/233
- [x] Research where to add the backend part of the migration tool - https://github.com/SAP/xsk/issues/234
- [x] Research what commands are invoked by the migration tool - https://github.com/SAP/xsk/issues/236
- [x] Create a PoC of the backend part of the migration tools - https://github.com/SAP/xsk/issues/235
- [x] Create a service for listing Delivery Units - https://github.com/SAP/xsk/issues/246
- [x] Create a service for openning a DB tunnel to the client provided HANA - https://github.com/SAP/xsk/issues/247
- [x] Provide a search functionality in the Delivery Units UI dropdown component - https://github.com/SAP/xsk/issues/248
- [x] Connect existing migration UI to the backend - https://github.com/SAP/xsk/issues/269
- [x] Hide passwords by default and provide a visibility button - https://github.com/SAP/xsk/issues/270
