### ISSUE TITLE
Keep synchronization state for each artifact

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#768]
Related to https://github.com/eclipse/dirigible/issues/1277 and https://github.com/eclipse/dirigible/issues/1278

XSK needs to keep track of the synchronisation state of each artifact it tries to activate. This will help in troubleshooting and in determining the sequence of activation of artifacts - ie a view can't be activated because the table is in failed state.

Related to https://github.com/eclipse/dirigible/issues/1277 

XSK needs to keep track of the synchronisation state of each artifact it tries to activate. This will help in troubleshooting and in determining the sequence of activation of artifacts - ie a view can't be activated because the table is in failed state.

### Target
- [ ]  .calculationview
- [x]  .hdbdd --> each entity in the hdbdd file - fixed with #768 
- [x]  .hdbprocedure - fixed with #768 
- [x]  .hdbschema - fixed with #768 
- [x]  .hdbsequence - fixed with #768 
- [x]  .hdbsynonym - fixed with #768 
- [x]  .hdbtable - fixed with #768 
- [x]  .hdbtablefunction - fixed with #768 
- [x]  .hdbview - fixed with #768 

---
### For later
- [x]  .hdbstructure - to be addressed with #961
- [x]  .hdbti - to be addressed with #961
- [x]  .xsaccess - to be addressed with #961
- [x]  .xsapp - to be addressed with #961
- [x]  .xshttpdest - to be addressed with #961
- [x]  .xsjob - to be addressed with #961
- [x]  .xsjs - to be addressed with #961
- [x]  .xsjslib - to be addressed with #961
- [x]  .xsodata - to be addressed with #961
- [x]  .xsprivileges - to be addressed with #961
- [x]  .xssecurestore - to be addressed with #961
